package de.btu.openinfra.backend.db.daos.meta;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;

import de.btu.openinfra.backend.db.daos.MappingResult;
import de.btu.openinfra.backend.db.daos.OpenInfraDao;
import de.btu.openinfra.backend.db.daos.OpenInfraSchemas;
import de.btu.openinfra.backend.db.jpa.model.meta.Log;
import de.btu.openinfra.backend.db.pojos.meta.LogPojo;

/**
 * This class represents the Log and is used to access the underlying layer
 * generated by JPA.
 * 
 * @author <a href="http://www.b-tu.de">BTU</a> DBIS
 *
 */
public class LogDao
    extends OpenInfraDao<LogPojo, Log> {

    /**
     * This is the required constructor which calls the super constructor and in 
     * turn creates the corresponding entity manager.
     * 
     * @param schema           the required schema
     */
    public LogDao(OpenInfraSchemas schema) {
        super(null, schema, Log.class);
    }

    @Override
    public LogPojo mapToPojo(Locale locale, Log l) {
        return mapPojoStatically(l);
    }
    
    /**
     * This method implements the method mapToPojo in a static way.
     * 
     * @param at     the model object
     * @return       the POJO object when the model object is not null else null
     */
    public static LogPojo mapPojoStatically(Log l) {
        if(l != null) {
            LogPojo pojo = new LogPojo();
            String format = "yyyy-MM-dd'T'H:m:sZ";
            DateFormat df = new SimpleDateFormat(format);
            pojo.setUuid(l.getId());
            pojo.setUserId(l.getUserId());
            pojo.setUserName(l.getUserName());
            pojo.setCreatedOn(df.format(l.getCreatedOn()).toString()); 
            pojo.setLogger(LoggerDao.mapPojoStatically(l.getLoggerBean()));
            pojo.setLevel(LevelDao.mapPojoStatically(l.getLevelBean()));
            pojo.setMessage(l.getMessage());
            return pojo;
        } else {
            return null;
        }
    }

    @Override
    public MappingResult<Log> mapToModel(LogPojo pojo, Log log) {
        // TODO Auto-generated method stub
        return null;
    }
}
