package de.btu.openinfra.backend.db.daos.meta;

import java.util.Locale;

import de.btu.openinfra.backend.db.MappingResult;
import de.btu.openinfra.backend.db.OpenInfraSchemas;
import de.btu.openinfra.backend.db.daos.OpenInfraDao;
import de.btu.openinfra.backend.db.jpa.model.meta.Ports;
import de.btu.openinfra.backend.db.pojos.meta.PortsPojo;

/**
 * This class represents the Ports and is used to access the underlying layer
 * generated by JPA.
 *
 * @author <a href="http://www.b-tu.de">BTU</a> DBIS
 *
 */
public class PortsDao
    extends OpenInfraDao<PortsPojo, Ports> {

    /**
     * This is the required constructor which calls the super constructor and in
     * turn creates the corresponding entity manager.
     *
     * @param schema           the required schema
     */
    public PortsDao(OpenInfraSchemas schema) {
        super(null, schema, Ports.class);
    }

    @Override
    public PortsPojo mapToPojo(Locale locale, Ports p) {
        return mapPojoStatically(p);
    }

    /**
     * This method implements the method mapToPojo in a static way.
     *
     * @param at     the model object
     * @return       the POJO object when the model object is not null else null
     */
    public static PortsPojo mapPojoStatically(Ports p) {
        if (p != null) {
            PortsPojo pojo = new PortsPojo(p);
            pojo.setPort(p.getPort());
            return pojo;
        } else {
            return null;
        }
    }

    @Override
    public MappingResult<Ports> mapToModel(PortsPojo pojo, Ports ports) {
        if(pojo != null) {
            mapToModelStatically(pojo, ports);
            return new MappingResult<Ports>(ports.getId(), ports);
        }
        else {
            return null;
        }
    }

    /**
     * This method implements the method mapToModel in a static way.
     * @param pojo the POJO object
     * @param ports the pre initialized model object
     * @return return a corresponding JPA model object or null if the pojo
     * object is null
     */
    public static Ports mapToModelStatically(PortsPojo pojo, Ports ports) {
        Ports resultPorts = null;
        if(pojo != null) {
            resultPorts = ports;
            if(resultPorts == null) {
                resultPorts = new Ports();
                resultPorts.setId(pojo.getUuid());
            }
            resultPorts.setPort(pojo.getPort());
        }
        return resultPorts;
    }

    /**
     * Creates an empty ports pojo.
     * @return an empty ports pojo
     */
    public PortsPojo newPorts() {
       return newPojoStatically();
    }

    /**
     * This method implements the method newPorts in a static way.
     * @return an empty ports pojo
     */
    public static PortsPojo newPojoStatically() {
        return new PortsPojo();
    }
}
