package de.btu.openinfra.backend.db.daos.meta;

import java.util.Locale;

import de.btu.openinfra.backend.db.daos.MappingResult;
import de.btu.openinfra.backend.db.daos.OpenInfraDao;
import de.btu.openinfra.backend.db.daos.OpenInfraSchemas;
import de.btu.openinfra.backend.db.jpa.model.meta.Ports;
import de.btu.openinfra.backend.db.pojos.meta.PortsPojo;

/**
 * This class represents the Ports and is used to access the underlying layer 
 * generated by JPA.
 * 
 * @author <a href="http://www.b-tu.de">BTU</a> DBIS
 *
 */
public class PortsDao 
    extends OpenInfraDao<PortsPojo, Ports> {

    /**
     * This is the required constructor which calls the super constructor and in 
     * turn creates the corresponding entity manager.
     * 
     * @param schema           the required schema
     */
    public PortsDao(OpenInfraSchemas schema) {
        super(null, schema, Ports.class);
    }

    @Override
    public PortsPojo mapToPojo(Locale locale, Ports p) {
        return mapPojoStatically(p);
    }

    /**
     * This method implements the method mapToPojo in a static way.
     * 
     * @param at     the model object
     * @return       the POJO object when the model object is not null else null
     */
    public static PortsPojo mapPojoStatically(Ports p) {
        if (p != null) {
            PortsPojo pojo = new PortsPojo();
            pojo.setUuid(p.getId());
            pojo.setPort(p.getPort());
            return pojo;
        } else {
            return null;
        }
    }

    @Override
    public MappingResult<Ports> mapToModel(PortsPojo pojo, Ports ports) {
        // TODO Auto-generated method stub
        return null;
    }

}
