package de.btu.openinfra.backend.db.daos.meta;

import java.util.Locale;

import de.btu.openinfra.backend.db.MappingResult;
import de.btu.openinfra.backend.db.daos.OpenInfraDao;
import de.btu.openinfra.backend.db.daos.OpenInfraSchemas;
import de.btu.openinfra.backend.db.jpa.model.meta.Servers;
import de.btu.openinfra.backend.db.pojos.meta.ServersPojo;

/**
 * This class represents the Servers and is used to access the underlying layer 
 * generated by JPA.
 * 
 * @author <a href="http://www.b-tu.de">BTU</a> DBIS
 *
 */
public class ServersDao
    extends OpenInfraDao<ServersPojo, Servers> {

    /**
     * This is the required constructor which calls the super constructor and in 
     * turn creates the corresponding entity manager.
     * 
     * @param schema           the required schema
     */
    public ServersDao(OpenInfraSchemas schema) {
        super(null, schema, Servers.class);
    }

    @Override
    public ServersPojo mapToPojo(Locale locale, Servers s) {
        return mapPojoStatically(s);
    }

    /**
     * This method implements the method mapToPojo in a static way.
     * 
     * @param at     the model object
     * @return       the POJO object when the model object is not null else null
     */
    public static ServersPojo mapPojoStatically(Servers s) {
        if (s != null) {
            ServersPojo pojo = new ServersPojo();
            pojo.setUuid(s.getId());
            pojo.setTrid(s.getXmin());
            pojo.setServer(s.getServer());
            return pojo;
        } else {
            return null;
        }
    }

    @Override
    public MappingResult<Servers> mapToModel(ServersPojo pojo, Servers s) {
        // TODO Auto-generated method stub
        return null;
    }

}
