package de.btu.openinfra.backend.db.daos.meta;

import java.util.Locale;
import java.util.UUID;

import de.btu.openinfra.backend.db.MappingResult;
import de.btu.openinfra.backend.db.OpenInfraSchemas;
import de.btu.openinfra.backend.db.daos.OpenInfraDao;
import de.btu.openinfra.backend.db.jpa.model.meta.Servers;
import de.btu.openinfra.backend.db.pojos.meta.ServersPojo;
import de.btu.openinfra.backend.exception.OpenInfraEntityException;
import de.btu.openinfra.backend.exception.OpenInfraExceptionTypes;

/**
 * This class represents the Servers and is used to access the underlying layer
 * generated by JPA.
 *
 * @author <a href="http://www.b-tu.de">BTU</a> DBIS
 *
 */
public class ServersDao
    extends OpenInfraDao<ServersPojo, Servers> {

    /**
     * This is the required constructor which calls the super constructor and in
     * turn creates the corresponding entity manager.
     * @param currentProjectId The identifier of the current project.
     * @param schema           the required schema
     */
    public ServersDao(UUID currentProjectId, OpenInfraSchemas schema) {
        super(null, OpenInfraSchemas.META_DATA, Servers.class);
    }

    @Override
    public ServersPojo mapToPojo(Locale locale, Servers s) {
        if (s != null) {
            ServersPojo pojo = new ServersPojo(s);
            pojo.setServer(s.getServer());
            return pojo;
        } else {
            return null;
        }
    }

    @Override
    public MappingResult<Servers> mapToModel(ServersPojo pojo, Servers s) {
        if(pojo != null) {
            Servers resultServers = null;
            try {
                resultServers = s;
                if(resultServers == null) {
                    resultServers = new Servers();
                    resultServers.setId(pojo.getUuid());
                }
                resultServers.setServer(pojo.getServer());
            } catch (NullPointerException npe) {
                throw new OpenInfraEntityException(
                        OpenInfraExceptionTypes.MISSING_DATA_IN_POJO);
            }
            return new MappingResult<Servers>(
                    resultServers.getId(),
                    resultServers);
        }
        else {
            return null;
        }
    }

}
