package de.btu.openinfra.backend.db.daos.meta;

import java.util.Locale;

import de.btu.openinfra.backend.db.MappingResult;
import de.btu.openinfra.backend.db.daos.OpenInfraDao;
import de.btu.openinfra.backend.db.daos.OpenInfraSchemas;
import de.btu.openinfra.backend.db.jpa.model.meta.Settings;
import de.btu.openinfra.backend.db.pojos.meta.SettingsPojo;

/**
 * This class represents the Settings and is used to access the underlying 
 * layer generated by JPA.
 * 
 * @author <a href="http://www.b-tu.de">BTU</a> DBIS
 *
 */
public class SettingsDao
    extends OpenInfraDao<SettingsPojo, Settings> {

    /**
     * This is the required constructor which calls the super constructor and in 
     * turn creates the corresponding entity manager.
     * 
     * @param schema           the required schema
     */
    public SettingsDao(OpenInfraSchemas schema) {
        super(null, schema, Settings.class);
    }
    
    @Override
    public SettingsPojo mapToPojo(Locale locale, Settings s) {
        return mapPojoStatically(s);
    }

    /**
     * This method implements the method mapToPojo in a static way.
     * 
     * @param at     the model object
     * @return       the POJO object when the model object is not null else null
     */
    public static SettingsPojo mapPojoStatically(Settings s) {
        if (s != null) {
            SettingsPojo pojo = new SettingsPojo();
            pojo.setUuid(s.getId());
            pojo.setTrid(s.getXmin());
            pojo.setKey(s.getKey());
            pojo.setUpdatedOn(s.getUpdatedOn());
            pojo.setValue(s.getValue());
            pojo.setProject(ProjectsDao.mapPojoStatically(s.getProject()));
            return pojo;
        } else {
            return null;
        }
    }

    @Override
    public MappingResult<Settings> mapToModel(SettingsPojo pojo, Settings s) {
        // TODO Auto-generated method stub
        return null;
    }

}
