package de.btu.openinfra.backend.db.daos;

import java.util.Locale;
import java.util.UUID;

import de.btu.openinfra.backend.db.jpa.model.AttributeType;
import de.btu.openinfra.backend.db.jpa.model.AttributeTypeXAttributeType;
import de.btu.openinfra.backend.db.pojos.AttributeTypeAssociationPojo;

/**
 * This class represents the AttributeTypeAssociation and is used to access the
 * underlying layer generated by JPA.
 *
 * @author <a href="http://www.b-tu.de">BTU</a> DBIS
 *
 */
public class AttributeTypeAssociationDao
	extends OpenInfraValueValueDao<AttributeTypeAssociationPojo,
	AttributeTypeXAttributeType, AttributeType, AttributeType> {

	/**
	 * This is the required constructor which calls the super constructor and in
	 * turn creates the corresponding entity manager.
	 *
	 * @param currentProjectId the current project id (this should be null when
	 *                         the system schema is selected)
	 * @param schema           the required schema
	 */
	public AttributeTypeAssociationDao(
			UUID currentProjectId,
			OpenInfraSchemas schema) {
		super(currentProjectId, schema, AttributeTypeXAttributeType.class,
				AttributeType.class, AttributeType.class);
	}

	@Override
	public AttributeTypeAssociationPojo mapToPojo(
			Locale locale,
			AttributeTypeXAttributeType association) {
		return mapToPojoStatically(locale, association);
	}

	@Override
	public MappingResult<AttributeTypeXAttributeType> mapToModel(
			AttributeTypeAssociationPojo pojoObject,
			AttributeTypeXAttributeType modelObject) {
		// TODO Auto-generated method stub
		return null;
	}
	
	/**
	 * This method implements the method mapToPojo in a static way.
	 * 
	 * @param locale       the requested language as Java.util locale
	 * @param association  the model object
	 * @return             the POJO object when the model object is not null
	 *                     else null
	 */
	public static AttributeTypeAssociationPojo mapToPojoStatically(
			Locale locale,
			AttributeTypeXAttributeType association) {
		
		if(association != null) {
			AttributeTypeAssociationPojo pojo =
					new AttributeTypeAssociationPojo();
			
			pojo.setUuid(association.getId());
			pojo.setRelationship(ValueListValueDao.mapToPojoStatically(locale,
					association.getValueListValue()));
			pojo.setAssociatedAttributeType(
				AttributeTypeDao.mapToPojoStatically(locale,
				association.getAttributeType2Bean()));
			
			return pojo;
		}
		else {
			return null;
		}
	}

}
