package de.btu.openinfra.backend.db.daos;

import java.util.Locale;
import java.util.UUID;

import de.btu.openinfra.backend.db.MappingResult;
import de.btu.openinfra.backend.db.OpenInfraSchemas;
import de.btu.openinfra.backend.db.jpa.model.AttributeTypeGroup;
import de.btu.openinfra.backend.db.jpa.model.AttributeTypeGroupToTopicCharacteristic;
import de.btu.openinfra.backend.db.jpa.model.TopicCharacteristic;
import de.btu.openinfra.backend.db.pojos.AttributeTypeGroupToTopicCharacteristicPojo;

/**
 * This class represents the AttributeTypeGroupToTopicCharacteristic and is used
 * to access the underlying layer generated by JPA.
 *
 * @author <a href="http://www.b-tu.de">BTU</a> DBIS
 *
 */
public class AttributeTypeGroupToTopicCharacteristicDao extends
	OpenInfraValueValueDao<AttributeTypeGroupToTopicCharacteristicPojo,
	AttributeTypeGroupToTopicCharacteristic, TopicCharacteristic,
	AttributeTypeGroup> {

	/**
	 * This is the required constructor which calls the super constructor and in
	 * turn creates the corresponding entity manager.
	 *
	 * @param currentProjectId the current project id (this should be null when
	 *                         the system schema is selected)
	 * @param schema           the required schema
	 */
	public AttributeTypeGroupToTopicCharacteristicDao(
			UUID currentProjectId,
			OpenInfraSchemas schema) {
		super(currentProjectId,
		      schema,
			  AttributeTypeGroupToTopicCharacteristic.class,
			  TopicCharacteristic.class, AttributeTypeGroup.class);
	}

	@Override
	public AttributeTypeGroupToTopicCharacteristicPojo mapToPojo(
			Locale locale,
			AttributeTypeGroupToTopicCharacteristic atg) {
		return mapToPojoStatically(locale, atg,
		        new MetaDataDao(currentProjectId, schema));
	}

	/**
	 * This method implements the method mapToPojo in a static way.
	 *
	 * @param locale the requested language as Java.util locale
	 * @param atgttc    the model object
	 * @param mdDao  the meta data DAO
	 * @return       the POJO object when the model object is not null else null
	 */
	public static AttributeTypeGroupToTopicCharacteristicPojo
		mapToPojoStatically(
				Locale locale,
				AttributeTypeGroupToTopicCharacteristic atgttc,
				MetaDataDao mdDao) {
	    if (atgttc != null) {
    		AttributeTypeGroupToTopicCharacteristicPojo pojo =
    				new AttributeTypeGroupToTopicCharacteristicPojo();

    		// set meta data if exists
            try {
                pojo.setMetaData(mdDao.read(atgttc.getId()).getData());
            } catch (NullPointerException npe) { /* do nothing */ }

    		pojo.setAttributeTypeGroup(
    		        AttributeTypeGroupDao.mapToPojoStatically(
    		                locale,
    		                atgttc.getAttributeTypeGroup(),
    		                null));
    		pojo.setMultiplicity(MultiplicityDao.mapToPojoStatically(
    				atgttc.getMultiplicityBean(),
    				null));
    		pojo.setTopicCharacteristicId(atgttc.getTopicCharacteristic().getId());

    		if(atgttc.getOrder() != null) {
    			pojo.setOrder(atgttc.getOrder());
    		}

    		pojo.setUuid(atgttc.getId());
    		pojo.setTrid(atgttc.getXmin());
    		return pojo;
	    } else {
	        return null;
	    }
	}

	@Override
	public MappingResult<AttributeTypeGroupToTopicCharacteristic> mapToModel(
			AttributeTypeGroupToTopicCharacteristicPojo pojo,
			AttributeTypeGroupToTopicCharacteristic atg) {

        // TODO set the model values

        // return the model as mapping result
        return new MappingResult<AttributeTypeGroupToTopicCharacteristic>(
                atg.getId(), atg);
	}

}
