package de.btu.openinfra.backend.db.daos;

import java.util.Locale;
import java.util.UUID;

import de.btu.openinfra.backend.db.MappingResult;
import de.btu.openinfra.backend.db.OpenInfraSchemas;
import de.btu.openinfra.backend.db.jpa.model.AttributeType;
import de.btu.openinfra.backend.db.jpa.model.AttributeTypeGroup;
import de.btu.openinfra.backend.db.jpa.model.AttributeTypeToAttributeTypeGroup;
import de.btu.openinfra.backend.db.pojos.AttributeTypeToAttributeTypeGroupPojo;

/**
 * This class represents the AttributeTypeToAttributeTypeGroup and is used to
 * access the underlying layer generated by JPA.
 *
 * @author <a href="http://www.b-tu.de">BTU</a> DBIS
 *
 */
public class AttributeTypeToAttributeTypeGroupDao extends
	OpenInfraValueValueDao<AttributeTypeToAttributeTypeGroupPojo,
	AttributeTypeToAttributeTypeGroup, AttributeTypeGroup, AttributeType> {

	/**
	 * This is the required constructor which calls the super constructor and in
	 * turn creates the corresponding entity manager.
	 *
	 * @param currentProjectId the current project id (this should be null when
	 *                         the system schema is selected)
	 * @param schema           the required schema
	 */
	public AttributeTypeToAttributeTypeGroupDao(
			UUID currentProjectId,
			OpenInfraSchemas schema) {
		super(currentProjectId,
			  schema,
			  AttributeTypeToAttributeTypeGroup.class,
			  AttributeTypeGroup.class,
			  AttributeType.class);
	}

	@Override
	public AttributeTypeToAttributeTypeGroupPojo mapToPojo(
			Locale locale,
			AttributeTypeToAttributeTypeGroup attatg) {
		AttributeTypeToAttributeTypeGroupPojo pojo =
				new AttributeTypeToAttributeTypeGroupPojo(attatg);

		pojo.setAttributeType(new AttributeTypeDao(
		        currentProjectId,
		        schema).mapToPojo(
		                locale,
		                attatg.getAttributeType()));
		pojo.setAttributeTypeGroupId(attatg.getId());
		pojo.setDefaultValue(new ValueListValueDao(
		        currentProjectId,
		        schema).mapToPojo(
		                locale,
		                attatg.getValueListValue()));
		pojo.setMultiplicity(new MultiplicityDao(
		        currentProjectId,
		        schema).mapToPojo(
		                null,
		                attatg.getMultiplicityBean()));
		pojo.setOrder(attatg.getOrder());
		return pojo;
	}

	@Override
	public MappingResult<AttributeTypeToAttributeTypeGroup> mapToModel(
			AttributeTypeToAttributeTypeGroupPojo pojo,
			AttributeTypeToAttributeTypeGroup at) {

        // TODO set the model values

        // return the model as mapping result
        return new MappingResult<AttributeTypeToAttributeTypeGroup>(
                at.getId(), at);
	}

}
