package de.btu.openinfra.backend.db.daos;

import java.util.Locale;
import java.util.UUID;

import de.btu.openinfra.backend.db.jpa.model.PtFreeText;
import de.btu.openinfra.backend.db.pojos.DescriptionPojo;

/**
 * This class represents the Description of an OpenInfRA object and is used to 
 * access the underlying layer generated by JPA.
 * 
 * @author <a href="http://www.b-tu.de">BTU</a> DBIS
 *
 */
public class DescriptionDao extends PtFreeTextDao<DescriptionPojo> {

	/**
	 * This is the required constructor which calls the super constructor and in 
	 * turn creates the corresponding entity manager.
	 * 
	 * @param currentProjectId the current project id (this should be null when 
	 *                         the system schema is selected)
	 * @param schema           the required schema
	 */
	public DescriptionDao(UUID currentProjectId, OpenInfraSchemas schema) {
		super(currentProjectId, schema, DescriptionPojo.class);
	}
	
	/**
	 * This method implements the method mapToPojo in a static way.
	 * 
	 * @param locale the requested language as Java.util locale
	 * @param ptf    the model object
	 * @return       the POJO object when the model object is not null else null
	 */
	public static DescriptionPojo mapToPojoStatically(
			Locale locale, 
			PtFreeText ptf) {
		UUID id = null;
		if(ptf != null) {
			id = ptf.getId();
		} // end if
		return new DescriptionPojo(
				mapToLocalizedStringStatically(locale, ptf),
				id);
	}

}
