package de.btu.openinfra.backend.db.daos;

import java.util.Locale;
import java.util.UUID;

import de.btu.openinfra.backend.db.jpa.model.PtFreeText;
import de.btu.openinfra.backend.db.pojos.ValuePojo;

/**
 * This class represents the Value of an OpenInfRA object and is used to access 
 * the underlying layer generated by JPA.
 * 
 * @author <a href="http://www.b-tu.de">BTU</a> DBIS
 *
 */
public class ValueDao extends PtFreeTextDao<ValuePojo>{

	/**
	 * This is the required constructor which calls the super constructor and in 
	 * turn creates the corresponding entity manager.
	 * 
	 * @param currentProjectId the current project id (this should be null when 
	 *                         the system schema is selected)
	 * @param schema           the required schema
	 */
	protected ValueDao(UUID currentProjectId, OpenInfraSchemas schema) {
		super(currentProjectId, schema, ValuePojo.class);
	}
	
	/**
	 * 
	 * @param locale
	 * @param ptf
	 * @return
	 */
	public static ValuePojo mapToPojoStatically(
			Locale locale, 
			PtFreeText ptf) {
		UUID id = null;
		if(ptf != null) {
			id = ptf.getId();
		} // end if
		return new ValuePojo(mapToLocalizedStringStatically(locale, ptf), id);
	}

}
